### ISSUE TITLE
takeref.py no output

### ISSUE THREAD

**Issue by thedam** [VUmcCGP/wisexome#4]
In every step there's something wrong in the code.
```

tChroms = [] #[str(x) for x in range(1,23)]
tChroms.append('X')

for tChrom in tChroms:
	curRef = dict()
	for rChrom in range(1,23):
		if tChrom != rChrom:

```
Firstly you create an empty array, then iterate over it.

If it would be like this: 
` tChroms = [str(x) for x in range(1,23)]
`
then 
`tChrom != rChrom`
is always True

Annoying repository, nothing is working and nobody updates it.

Regards,
Damian Loska

**Comment by rstraver** [comment]
Hi Damian,

You are correct on that error. I originally wrote everything for just autosomal chromosomes, then added some X based testing later on but never had time to fix everything nicely, causing bugs as you mention here.

I understand your frustration, but I do not work at the VUmc anymore and it appears no one took over this project (yet). While I can accept fixes for problems you mention, I  can't test them myself as I also have no data (it's patient data and all that). Perhaps your best move would be to fork the project and share your fixes with the world.

Considering my lack of response until now: his project turned out to be not on my watch list so all issues raised went unnoticed. Sorry for that.

**Comment by thedam** [comment]
Hi Roy, 

Thanks for the answer. 
I can detect small errors in the code, however I've never seen the final result, so after my fixes I would be afraid if the final output is correct.

**Comment by rstraver** [comment]
If you want I can check some of your intermediate files as a sanity check, and try to answer any problem to the best of my ability.

I'm happy you are willing to take the effort of finding the errors and reporting them, I have to admit the current code isn't really fast or very clean.

**Comment by thedam** [comment]
Well, I just make some effort to run it, and to see the results;)
ps. I wrote you on email specified in your github account. If it doesn't work, I've sent you my email on LinkedIn (hope they allow to send emails in the first message). I'd have one more question, that may be also helpful the tutorial.
Thanks
